In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from splinter import Browser

In [2]:
# Drivers`s Path
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [3]:
# Go to NCAA Boxscore through splinter module
score_url = 'https://www.ncaa.com/game/lacrosse-women/d1/2019/05/02/army-navy/boxscore'
browser.visit(score_url)

In [4]:
html = browser.html
#response = requests.get(url)
soup = BeautifulSoup(html, 'lxml')
tables = pd.read_html(html)
box_table = tables[1]
box_table

    No               Name  POS  G  A  SH  SOG  GB
0   10   SAMANTHA STEWART    M  1  2   4    3   2
1   13     MANUELA CORTES    M  1  0   5    2   0
2   21   CAROLINE RAYMOND    M  1  1   4    1   1
3   23  LAUREN BREDENBURG    M  0  0   0    0   1
4   44        RILEE SCOTT    M  1  0   5    1   2
5   42       MADDIE BURNS    G  0  0   0    0   1
6    1          NIA CRUMP    D  0  0   0    0   0
7    5        RYAN MURPHY    D  0  0   0    0   0
8   35     TAYLOR KORPELA    D  0  0   0    0   1
9   18      OLIVIA CARTER    A  0  0   0    0   1
10  28     JACKIE BRATTAN    A  4  0  10    7   0
11  34  JULIANA DWORSCHAK    A  0  0   0    0   0
12   7       BETH HOFMANN  NaN  0  1   0    0   0
13  15      CAMERON MANOR  NaN  1  0   1    1   0
14  16      MEGAN RAFTERY  NaN  0  0   1    0   0
15  25     TAYLOR ANDREWS  NaN  1  0   1    1   0
16  26      KELSEA KRAUSS  NaN  0  0   0    0   0
17  39     NIKKI POLHAMUS  NaN  0  0   0    0   0
18  48     HANNAH SHIFLET  NaN  0  0   0    0   0

In [5]:
  # Read the BoxScore Data and store Pandas data frame
box_table_df = box_table

In [6]:
print(box_table_df)

    No               Name  POS  G  A  SH  SOG  GB
0   10   SAMANTHA STEWART    M  1  2   4    3   2
1   13     MANUELA CORTES    M  1  0   5    2   0
2   21   CAROLINE RAYMOND    M  1  1   4    1   1
3   23  LAUREN BREDENBURG    M  0  0   0    0   1
4   44        RILEE SCOTT    M  1  0   5    1   2
5   42       MADDIE BURNS    G  0  0   0    0   1
6    1          NIA CRUMP    D  0  0   0    0   0
7    5        RYAN MURPHY    D  0  0   0    0   0
8   35     TAYLOR KORPELA    D  0  0   0    0   1
9   18      OLIVIA CARTER    A  0  0   0    0   1
10  28     JACKIE BRATTAN    A  4  0  10    7   0
11  34  JULIANA DWORSCHAK    A  0  0   0    0   0
12   7       BETH HOFMANN  NaN  0  1   0    0   0
13  15      CAMERON MANOR  NaN  1  0   1    1   0
14  16      MEGAN RAFTERY  NaN  0  0   1    0   0
15  25     TAYLOR ANDREWS  NaN  1  0   1    1   0
16  26      KELSEA KRAUSS  NaN  0  0   0    0   0
17  39     NIKKI POLHAMUS  NaN  0  0   0    0   0
18  48     HANNAH SHIFLET  NaN  0  0   0    0   0

In [7]:
# Go to NCAA Play by play  through splinter module
score_url = 'https://www.ncaa.com/game/lacrosse-women/d1/2019/05/02/army-navy/play-by-play'
browser.visit(score_url)

In [8]:
# html = browser.html
# #response = requests.get(url)
# soup = BeautifulSoup(html, 'lxml')
# all_rows = soup.find_all('tr')
# for row in all_rows:
#     try:
#         print(row.find(class_="time").text)
#         img = row.find(class_="team")
#         print(img.find("img")["title"])
#         print(row.find(class_="description").text)
#         print(row.find(class_="score").text)
        
#     except:
#         pass

# #tables = pd.read_html(html)
# #away_table = tables[1]
# #away_table

In [84]:
html = browser.html
#response = requests.get(url)
soup = BeautifulSoup(html, 'lxml')
team_rows_list=[]

team_rows = soup.find_all('tr')

for row in team_rows:

    try:
        img = row.find(class_="team")
        print(img.find("img")["title"])
        team_rows_list[team_rows]
           
    except:
         pass

Army
Navy
Army
Army
Army
Navy
Army
Navy
Army
Army
Navy
Navy
Navy
Navy
Army
Navy
Navy
Navy
Navy
Army
Navy
Army
Navy
Army
Navy
Navy
Navy
Army
Navy
Army
Navy
Army
Navy
Navy
Army
Navy
Navy
Navy
Navy
Navy
Navy
Navy
Navy
Army
Army
Navy
Navy
Army
Navy
Army
Navy
Navy
Navy
Army
Army
Army
Army
Army
Navy
Navy
Navy
Navy
Navy
Navy
Navy
Navy
Navy
Army
Navy
Navy
Army
Army
Army
Army
Army
Navy
Army
Navy
Army
Army
Army
Navy
Army
Army
Army
Army
Army
Army
Navy
Navy
Navy
Navy
Navy
Army
Army
Army
Army
Navy
Army
Navy
Army
Army
Navy
Army
Navy
Army
Navy
Navy
Navy
Navy
Navy
Army
Navy
Army
Army
Navy
Army
Army
Navy
Navy
Navy
Navy
Navy
Army
Navy
Army
Army
Army
Navy
Army
Navy
Army
Army
Navy
Army
Army
Army
Navy
Navy
Navy
Army
Army
Army
Navy
Navy
Navy
Navy
Navy
Navy
Army
Army
Navy
Army
Navy
Navy
Navy
Navy
Army
Army
Navy
Navy
Army
Navy
Army
Navy
Navy
Navy
Navy
Navy
Navy
Army
Army
Navy
Navy
Army
Army
Navy
Army
Navy
Army
Army
Navy
Army
Navy
Navy
Army
Navy
Army
Navy
Navy
Army
Navy
Navy
Army
Navy
Army
Army
Navy
Army
Navy
Navy
Navy
Army
Army
Navy
Army
Navy
Navy
Army
Army
Navy
Navy
Navy
Navy
Army
Army
Navy
Navy
Army
Army
Navy
Navy
Navy
Navy
Navy
Army
Navy
Navy
Navy
Navy
Navy
Army
Army
Navy
Army
Navy
Army
Army
Navy
Army
Army
Navy
Navy
Navy
Navy

In [85]:
type(team_rows_list)

list

In [86]:
df = team_rows_list[0]

IndexError: list index out of range

In [75]:
  # Read the Team Data list and store Pandas data frame
team_table_df = pd.DataFrame(team_rows_list)

In [63]:
team_table_df

Empty DataFrame
Columns: []
Index: []

In [64]:
html = browser.html
#response = requests.get(url)
soup = BeautifulSoup(html, 'lxml')
tables = pd.read_html(html)
noteam_table = tables[1]
noteam_table

      Time  Team                                               Play Score
0    30:00   NaN                  Burns, Maddie at goalie for ARMY.   NaN
1    30:00   NaN               Harchelroad, Gab at goalie for NAVY.   NaN
2    00:00   NaN           Draw control by ARMY Dworschak, Juliana.   NaN
3    29:16   NaN           Shot by ARMY Stewart, Samantha HIT POST.   NaN
4    29:06   NaN           Ground ball pickup by ARMY Scott, Rilee.   NaN
5    00:00   NaN                        Foul on NAVY Harris, Kayla.   NaN
6    28:36   NaN  GOAL by ARMY Brattan, Jackie (FIRST GOAL), goa...   1-0
7    00:00   NaN            Draw control by NAVY Heyward, Annalise.   NaN
8    00:00   NaN                      Foul on ARMY Korpela, Taylor.   NaN
9    00:00   NaN                           Foul on ARMY Crump, Nia.   NaN
10   28:15   NaN                    Free position attempt for NAVY.   NaN
11   28:12   NaN  GOAL by NAVY Larkin, Kelly (FPGOAL) {free posi...   1-1
12   00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
13   27:30   NaN  GOAL by NAVY Larkin, Kelly, goal number 57 for...   1-2
14   00:00   NaN               Yellow card on ARMY Korpela, Taylor.   NaN
15   00:00   NaN            Draw control by NAVY O'Sullivan, Andie.   NaN
16   27:15   NaN  Shot by NAVY O'Sullivan, Andie, SAVE Burns, Ma...   NaN
17   27:12   NaN          Ground ball pickup by NAVY Larkin, Kelly.   NaN
18   27:02   NaN  GOAL by NAVY Irwin, Natalie (MAN-UP), Assist b...   1-3
19   00:00   NaN              Draw control by ARMY Brattan, Jackie.   NaN
20   00:00   NaN                        Foul on NAVY Harris, Kayla.   NaN
21   26:13   NaN  Shot by ARMY Stewart, Samantha, SAVE Harchelro...   NaN
22   26:11   NaN         Ground ball pickup by NAVY Irwin, Natalie.   NaN
23   00:00   NaN               Yellow card on ARMY Andrews, Taylor.   NaN
24   25:57   NaN                        Clear attempt by NAVY good.   NaN
25   25:26   NaN                 Shot by NAVY Roelofs, Reagan WIDE.   NaN
26   25:24   NaN        Ground ball pickup by NAVY Victory, Nicole.   NaN
27   00:00   NaN                   Foul on ARMY Bredenburg, Lauren.   NaN
28   25:15   NaN    Shot by NAVY Harris, Kayla, SAVE Burns, Maddie.   NaN
29   24:47   NaN  Turnover by ARMY Scott, Rilee (caused by O'Sul...   NaN
..     ...   ...                                                ...   ...
115  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
116  00:00   NaN                   Foul on ARMY Bredenburg, Lauren.   NaN
117  00:00   NaN                   Foul on ARMY Bredenburg, Lauren.   NaN
118  05:34   NaN                    Free position attempt for NAVY.   NaN
119  05:32   NaN  GOAL by NAVY O'Sullivan, Andie (FPGOAL) {free ...   5-9
120  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
121  05:09   NaN  GOAL by NAVY Larkin, Kelly, goal number 59 for...  5-10
122  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
123  00:00   NaN                      Foul on ARMY Cortes, Manuela.   NaN
124  04:20   NaN    Shot by NAVY Harris, Kayla, SAVE Burns, Maddie.   NaN
125  04:06   NaN                        Clear attempt by ARMY good.   NaN
126  03:36   NaN                 Shot by ARMY Brattan, Jackie HIGH.   NaN
127  03:25   NaN                    Free position attempt for ARMY.   NaN
128  00:00   NaN                             Foul on NAVY Eby, Gil.   NaN
129  03:22   NaN  GOAL by ARMY Brattan, Jackie (FPGOAL) {free po...  6-10
130  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
131  00:00   NaN                   Foul on ARMY Dworschak, Juliana.   NaN
132  00:00   NaN                    Foul on ARMY Raymond, Caroline.   NaN
133  02:45   NaN                  Turnover by NAVY Victory, Nicole.   NaN
134  02:43   NaN      Ground ball pickup by ARMY Stewart, Samantha.   NaN
135  02:31   NaN                        Clear attempt by ARMY good.   NaN
136  02:06   NaN  Shot by ARMY Brattan, Jackie, SAVE Harchelroad...   NaN
137  02:04   NaN       Ground ball pickup by NAVY Harchelroad, Gab.   NaN
138  01:51   NaN                        Clear attempt by NAVY good.   NaN
139  01:43   NaN   Shot by NAVY Valenti, Marie, SAVE Burns, Maddie.   NaN
140  01:35   NaN     Ground ball pickup by ARMY Bredenburg, Lauren.   NaN
141  00:51   NaN                        Clear attempt by ARMY good.   NaN
142  00:34   NaN                   Turnover by ARMY Carter, Olivia.   NaN
143  00:04   NaN  GOAL by NAVY Larkin, Kelly, goal number 60 for...  6-11
144  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN

[145 rows x 4 columns]

In [65]:
  # Read the BoxScore Data and store Pandas data frame
noteam_table_df = noteam_table

In [66]:
print(noteam_table_df)

      Time  Team                                               Play Score
0    30:00   NaN                  Burns, Maddie at goalie for ARMY.   NaN
1    30:00   NaN               Harchelroad, Gab at goalie for NAVY.   NaN
2    00:00   NaN           Draw control by ARMY Dworschak, Juliana.   NaN
3    29:16   NaN           Shot by ARMY Stewart, Samantha HIT POST.   NaN
4    29:06   NaN           Ground ball pickup by ARMY Scott, Rilee.   NaN
5    00:00   NaN                        Foul on NAVY Harris, Kayla.   NaN
6    28:36   NaN  GOAL by ARMY Brattan, Jackie (FIRST GOAL), goa...   1-0
7    00:00   NaN            Draw control by NAVY Heyward, Annalise.   NaN
8    00:00   NaN                      Foul on ARMY Korpela, Taylor.   NaN
9    00:00   NaN                           Foul on ARMY Crump, Nia.   NaN
10   28:15   NaN                    Free position attempt for NAVY.   NaN
11   28:12   NaN  GOAL by NAVY Larkin, Kelly (FPGOAL) {free posi...   1-1
12   00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
13   27:30   NaN  GOAL by NAVY Larkin, Kelly, goal number 57 for...   1-2
14   00:00   NaN               Yellow card on ARMY Korpela, Taylor.   NaN
15   00:00   NaN            Draw control by NAVY O'Sullivan, Andie.   NaN
16   27:15   NaN  Shot by NAVY O'Sullivan, Andie, SAVE Burns, Ma...   NaN
17   27:12   NaN          Ground ball pickup by NAVY Larkin, Kelly.   NaN
18   27:02   NaN  GOAL by NAVY Irwin, Natalie (MAN-UP), Assist b...   1-3
19   00:00   NaN              Draw control by ARMY Brattan, Jackie.   NaN
20   00:00   NaN                        Foul on NAVY Harris, Kayla.   NaN
21   26:13   NaN  Shot by ARMY Stewart, Samantha, SAVE Harchelro...   NaN
22   26:11   NaN         Ground ball pickup by NAVY Irwin, Natalie.   NaN
23   00:00   NaN               Yellow card on ARMY Andrews, Taylor.   NaN
24   25:57   NaN                        Clear attempt by NAVY good.   NaN
25   25:26   NaN                 Shot by NAVY Roelofs, Reagan WIDE.   NaN
26   25:24   NaN        Ground ball pickup by NAVY Victory, Nicole.   NaN
27   00:00   NaN                   Foul on ARMY Bredenburg, Lauren.   NaN
28   25:15   NaN    Shot by NAVY Harris, Kayla, SAVE Burns, Maddie.   NaN
29   24:47   NaN  Turnover by ARMY Scott, Rilee (caused by O'Sul...   NaN
..     ...   ...                                                ...   ...
115  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
116  00:00   NaN                   Foul on ARMY Bredenburg, Lauren.   NaN
117  00:00   NaN                   Foul on ARMY Bredenburg, Lauren.   NaN
118  05:34   NaN                    Free position attempt for NAVY.   NaN
119  05:32   NaN  GOAL by NAVY O'Sullivan, Andie (FPGOAL) {free ...   5-9
120  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
121  05:09   NaN  GOAL by NAVY Larkin, Kelly, goal number 59 for...  5-10
122  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
123  00:00   NaN                      Foul on ARMY Cortes, Manuela.   NaN
124  04:20   NaN    Shot by NAVY Harris, Kayla, SAVE Burns, Maddie.   NaN
125  04:06   NaN                        Clear attempt by ARMY good.   NaN
126  03:36   NaN                 Shot by ARMY Brattan, Jackie HIGH.   NaN
127  03:25   NaN                    Free position attempt for ARMY.   NaN
128  00:00   NaN                             Foul on NAVY Eby, Gil.   NaN
129  03:22   NaN  GOAL by ARMY Brattan, Jackie (FPGOAL) {free po...  6-10
130  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN
131  00:00   NaN                   Foul on ARMY Dworschak, Juliana.   NaN
132  00:00   NaN                    Foul on ARMY Raymond, Caroline.   NaN
133  02:45   NaN                  Turnover by NAVY Victory, Nicole.   NaN
134  02:43   NaN      Ground ball pickup by ARMY Stewart, Samantha.   NaN
135  02:31   NaN                        Clear attempt by ARMY good.   NaN
136  02:06   NaN  Shot by ARMY Brattan, Jackie, SAVE Harchelroad...   NaN
137  02:04   NaN       Ground ball pickup by NAVY Harchelroad, Gab.   NaN
138  01:51   NaN                        Clear attempt by NAVY good.   NaN
139  01:43   NaN   Shot by NAVY Valenti, Marie, SAVE Burns, Maddie.   NaN
140  01:35   NaN     Ground ball pickup by ARMY Bredenburg, Lauren.   NaN
141  00:51   NaN                        Clear attempt by ARMY good.   NaN
142  00:34   NaN                   Turnover by ARMY Carter, Olivia.   NaN
143  00:04   NaN  GOAL by NAVY Larkin, Kelly, goal number 60 for...  6-11
144  00:00   NaN              Draw control by NAVY Roelofs, Reagan.   NaN

[145 rows x 4 columns]

In [58]:
 # Combine the data into a single dataset and display the data table for preview
playplay_df = pd.merge(team_table_df,noteam_table_df, on="city", how="left")
playplay_df.head()

KeyError: 'city'